# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sls-python

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  environment:
    user_table: User
    event_table: Event
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.user_table}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.event_table}"

functions:
  user_list:
    handler: user.list
    events:
      - http:
          path: user/list
          method: get
          cors: true

  user_create:
    handler: user.create
    events:
      - http:
          path: user/create
          method: post
          cors: true

  user_login:
    handler: user.login
    events:
      - http:
          path: user/login
          method: post
          cors: true

  create_event:
    handler: event.create
    events:
      - http:
          path: event/create
          method: post
          cors: true

  delete_event:
    handler: event.delete
    events:
      - http:
          path: event/delete/{id}
          method: delete
          cors: true

  update_event:
    handler: event.update
    events:
      - http:
          path: event/update/{id}
          method: put
          cors: true
